const JOB_LIST_UPDATE_INTERVAL = "JOB_LIST_UPDATE_INTERVAL";
const JOB_DETAIL_UPDATE_INTERVAL = "JOB_DETAIL_UPDATE_INTERVAL";
const TASK_LIST_UPDATE_INTERVAL = "TASK_LIST_UPDATE_INTERVAL";
const TASK_DETAIL_UPDATE_INTERVAL = "TASK_DETAIL_UPDATE_INTERVAL";
const COMMAND_LIST_UPDATE_INTERVAL = "TASK_DETAIL_UPDATE_INTERVAL";

export default {
  JOB_LIST_UPDATE_INTERVAL,
  JOB_DETAIL_UPDATE_INTERVAL,
  TASK_LIST_UPDATE_INTERVAL,
  TASK_DETAIL_UPDATE_INTERVAL,
  COMMAND_LIST_UPDATE_INTERVAL
};
